# Generated by Django 4.2.8 on 2023-12-27 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('job', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('referal_source', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'جراید'), (2, 'سایر مراجعان'), (3, 'تلویزیون'), (4, 'رادیو'), (5, 'پوستر'), (6, 'بروشور'), (7, 'تابلو های تبلیغاتی (بیلبورد)'), (8, 'اطلاع رسانی تلفنی (118)'), (9, 'خط 148 (صدای مشاور)'), (10, 'سایر')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('detail', models.TextField(max_length=2056)),
                ('avail', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه')], max_length=6)),
                ('specialty_field', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('interventions', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='patient_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conditions')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=63)),
                ('frequency', models.CharField(max_length=255)),
                ('start_time', models.DateField(default=datetime.datetime.now)),
                ('end_time', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_apt', models.DateField(default=datetime.date.today)),
                ('marital_status', models.PositiveSmallIntegerField(choices=[(1, 'مجرد'), (2, 'نامزد'), (3, 'عقد'), (4, 'متأهل'), (5, 'ازدواج موقت'), (6, 'تعدد زوجات'), (7, 'ازدواج مجدد'), (8, 'متارکه'), (9, 'مطلقه'), (10, 'بیوه')])),
                ('educational_status', models.PositiveSmallIntegerField(choices=[(1, '(سنین بالا)بی سواد'), (2, 'زیر سن مدرسه'), (3, 'پیش دبستانی'), (5, 'ابتدایی(دانش آموز)'), (6, '(دانش آموز)راهنمایی'), (7, '(دانش آموز)دبیرستان'), (8, 'ابتدایی(ترک تحصیل)'), (9, 'راهنمایی(ترک تحصیل)'), (10, 'دبیرستان(ترک تحصیل)'), (11, 'دیپلم و پیش دانشگاهی'), (12, 'دارای مدرک دانشگاهی'), (13, 'دانشجو'), (14, 'حوزوی')])),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.psychologist')),
            ],
        ),
        migrations.AddField(
            model_name='conditions',
            name='patient',
            field=models.ManyToManyField(through='core.patient_conditions', to='core.patient'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.CharField(choices=[('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM'), ('6:30 PM', '6:30 PM'), ('7 PM', '7 PM'), ('7:30 PM', '7:30 PM')], default='3 PM', max_length=10)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'نقدی'), (2, 'کارت')])),
                ('available_status', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.psychologist')),
            ],
        ),
    ]
