# Generated by Django 4.2.8 on 2023-12-29 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_conditions_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='job',
        ),
        migrations.AddField(
            model_name='dossier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='dossier',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
