# Generated by Django 4.2.8 on 2023-12-29 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_patient_address_remove_patient_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatment_plan',
            name='patient',
        ),
        migrations.AddField(
            model_name='medication',
            name='dossier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dossier'),
        ),
        migrations.AddField(
            model_name='treatment_plan',
            name='dossier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dossier'),
        ),
    ]
