# Generated by Django 4.2.8 on 2024-01-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_condition_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='patient',
        ),
    ]
